export declare const interpolationExpressionExp: RegExp;
export declare const spaceExp: RegExp;
export declare const attrStartExp: RegExp;
export declare const attrEndExp: RegExp;
export declare const eventStartExp: RegExp;
export declare const eventEndExp: RegExp;
export declare const tempvarExp: RegExp;
export declare const parsePipesExp: RegExp;
export declare const evalExp: RegExp;
